server:
  port: 8080

gemini:
  apiKey: AIzaSyCrfkqXPUsSQoz0IiukLxtv3tn3uO4T3T0
  ssl:
    trustAll: true
  tts:
    voiceName: Leda
  webclient:
    maxInMemorySizeBytes: 20971520

spring:
  codec:
    max-in-memory-size: 10MB

  main:
    web-application-type: servlet

  # Profile groups: when you run with "local", it will also enable "openai"
  # Same for "prod".
  profiles:
    group:
      local: local,openai
      prod: prod,openai

app:
  openai:
    api-base: https://api.openai.com/v1
    chat-model: gpt-4o-mini
    embed-model: text-embedding-3-small
    api-key: ${OPENAI_API_KEY:}

  ollama:
    api-base: http://localhost:11434
    chat-model: llama3.1

  s3:
    bucket: http://localhost:11434
    region: US

  google:
    api-key: ${GOOGLE_MAPS_API_KEY:}


  pixabay:
    api-key: 53590968-4d885133b419ce3d5a0e89ac3